### ISSUE TITLE
News Design

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#39]

**Comment by thepaleshadow** [comment]
PDFs of the full site comps for reference (Mobile and Desktop): @alxmrtnz @heyitsolivia 
https://www.dropbox.com/sh/7y5j38j4abp6r6p/AAAurRuIACCB4kgLT-DV8y8La?dl=0

**Comment by alxmrtnz** [comment]
@thepaleshadow looks good to me.

Only change I would say is to make the "Read More" links teal instead of navy so that it matches the other links like that on the site

for reference:
<img width="685" alt="screen shot 2016-04-12 at 1 15 23 pm" src="https://cloud.githubusercontent.com/assets/1167326/14469052/d06407f8-00b0-11e6-9e79-28fdc0dd3505.png">

I don't think you need to update the comp as it's a small change
